apiVersion: v2
name: ravhub
description: Official RavHub Helm Chart (Community & Enterprise)
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/ravhub/ravhub/main/apps/web/public/logo.png
dependencies:
  - name: postgresql
    version: 13.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
