apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ravhub.fullname" . }}-secrets
  labels:
    {{- include "ravhub.labels" . | nindent 4 }}
type: Opaque
data:
  {{- /* JWT Secret Logic: User Value -> Existing Secret -> Generate */}}
  {{- $secretName := printf "%s-secrets" (include "ravhub.fullname" .) }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  
  {{- $jwtSecret := "" }}
  {{- if .Values.auth.jwt.secret }}
    {{- $jwtSecret = .Values.auth.jwt.secret }}
  {{- else if hasKey $secretData "jwt-secret" }}
    {{- $jwtSecret = (get $secretData "jwt-secret") | b64dec }}
  {{- else }}
    {{- $jwtSecret = randAlphaNum 32 }}
  {{- end }}
  jwt-secret: {{ $jwtSecret | b64enc | quote }}

  {{- /* Database Password */}}
  {{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
  db-password: {{ .Values.externalDatabase.password | required "A valid .Values.externalDatabase.password is required if existingSecret is not set!" | b64enc | quote }}
  {{- end }}

  {{- /* Redis Password (Only for External Redis without existingSecret) */}}
  {{- if and (not .Values.redis.enabled) (not .Values.externalRedis.existingSecret) .Values.externalRedis.host }}
  redis-password: {{ .Values.externalRedis.password | default "" | b64enc | quote }}
  {{- end }}

  {{- /* S3 Secrets */}}
  {{- if eq .Values.storage.type "s3" }}
  s3-access-key: {{ .Values.storage.s3.accessKey | default "" | b64enc | quote }}
  s3-secret-key: {{ .Values.storage.s3.secretKey | default "" | b64enc | quote }}
  {{- end }}

  {{- /* Azure Secrets */}}
  {{- if eq .Values.storage.type "azure" }}
  azure-connection-string: {{ .Values.storage.azure.connectionString | default "" | b64enc | quote }}
  {{- end }}
